name: grab
on:
  workflow_dispatch:
  schedule:
    - cron: "30 * * * *"
jobs:
  test:
    runs-on: ubuntu-18.04
    name: grab
    steps:
      - name: download script
        run: "wget https://raw.githubusercontent.com/${{ github.repository }}/master/grab.js"
      - name: grab links
        run: "node ./grab.js"
      - name: update stream branch
        run: "sh ./update_stream.sh"
        env:
          GITHUB_TOKEN4: ${{ github.token }}
