name: grab
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "30 * * * *"
jobs:
  test:
    runs-on: ubuntu-latest
    name: grab
    steps:
      - name: download scripts
        run: "wget https://raw.githubusercontent.com/${{ github.repository }}/master/grab.js https://raw.githubusercontent.com/${{ github.repository }}/master/update_stream.sh"
      - name: grab links
        run: "node ./grab.js"
      - name: update stream branch
        run: "sh ./update_stream.sh"
        env:
          GITHUB_TOKEN: ${{ github.token }}
