name: grab
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "30 * * * *"
jobs:
  test:
    runs-on: ubuntu-18.04
    name: grab
    steps:
      - name: grab
        run: "node ./grab.js"
