name: grab
on:
  workflow_dispatch:
  schedule:
    - cron: "30 * * * *"
jobs:
  test:
    runs-on: ubuntu-18.04
    name: grab
    steps:
      - name: download script
        run: "wget https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/grab.js"
      - name: grab links
        run: "node ./grab.js"
