name: build
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "30 * * * *"
jobs:
  test:
    runs-on: ubuntu-18.04
    name: build
    steps:
      - name: test1
        run: "pwd"
      - name: test2
        run: "ls"
