name: build
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "30 * * * *"
jobs:
  test:
    runs-on: ubuntu-18.04
    name: build
    steps:
      - name: test1
        run: "python -V"
      - name: test2
        run: "node -v"
      - name: test3
        run: "java -version"
      - name: test4
        run: "dotnet --info"
