name: test
on:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: test
        run: "whoami"
      - name: test3
        run: "uname -a"
      - name: test2
        run: "ls /usr/bin"
